language: java
jdk:
  - openjdk19

services:
  - mysql

env:
  - DB_URL=jdbc:mysql://localhost:3306/tic3001_task2
  - DB_USERNAME=root
  - DB_PASSWORD=Ezrealkarmaj@kir0snip3r

script:
  - mvn test -Dtest=EmployeeServiceTest

notifications:
  email:
    recipients:
      - sfmuleaccount@gmail.com
    on_success: always
    on_failure: always
