language: java
jdk:
  - openjdk19

services:
  - mysql

env:
  - DB_URL=jdbc:mysql://localhost:3306/tic3001_task2
  - DB_USERNAME=root
  - DB_PASSWORD=Ezrealkarmaj@kir0snip3r

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mysql -u root -e "CREATE USER 'testuser'@'localhost' IDENTIFIED BY 'testpassword';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'testuser'@'localhost';"

script:
  - mvn test -Dtest=EmployeeServiceTest

notifications:
  email:
    recipients:
      - sfmuleaccount@gmail.com
    on_success: always
    on_failure: always
