name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: tic3001_task2
          MYSQL_USER: user
          MYSQL_PASSWORD: Ezrealkarmaj@kir0snip3r

    steps:
    - uses: actions/checkout@v2

    - name: Build with Maven
      run: mvn clean package

    - name: Test with MySQL
      env:
        DB_URL: jdbc:mysql://localhost:3306/tic3001_task2
        DB_USERNAME: user
        DB_PASSWORD: Ezrealkarmaj@kir0snip3r
      run: mvn test
